#!/bin/sh

echo "START"

cd $NEVERCODE_BUILD_OUTPUT_DIR
ls


echo "START"


- curl -X POST --data-binary @app-debug.apk -H "Authorization:Bearer $LAB_TOKEN" https://lab-api.nowsecure.com/build/


echo "Error if any is:"
echo $?

echo "trigger start"
curl \
-X POST \
-H 'Authorization:Bearer '$LAB_KEY \
https://lab-api.nowsecure.com/app/android/bscorp.appbase/assessment/
echo "trigger stop"
